import './globals.css';
import StoryblokProvider from '@/components/StoryblokProvider';
import SiteHeader from '@/components/SiteHeader';
import SiteFooter from '@/components/SiteFooter';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="sv">
			<body>
				<StoryblokProvider>
					<SiteHeader />
					{children}
					<SiteFooter />
				</StoryblokProvider>
			</body>
		</html>
	);
}
